### ISSUE TITLE
Initial setup and usage docs

### ISSUE THREAD

**Issue by jnorvell** [heavycircle/remark-obsidian#1]
I'm new to all this and am trying to use your library with ReactJS and the react-markdown / remark framework. 

Under your API section (in docs) you say to:

```
unified().use(remarkObsidian)
```

How can we import your library into ```remarkObsidian``` ?

I've tried 
```
import remarkObsidian from "@thecae/remark-obsidian";
```
but it cannot  be found.  I have used npm to install your lib, and it shows under my node_modules.

```
Could not find a declaration file for module '@thecae/remark-obsidian'. '/home/username/project/node_modules/@thecae/remark-obsidian/index.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/thecae__remark-obsidian` if it exists or add a new declaration (.d.ts) file containing `declare module '@thecae/remark-obsidian';`ts(7016)
```

**Comment by heavycircle** [comment]
Hey there John!

I went to test the issue you're having and I seem to be having the same issue.  I'm not sure if it's because of something I did when publishing to NPM or in the code itself.  I also notice it mainly gives me the issue when using TypeScript (since my parser was written in Javascript).

I'll look into getting this fixed.  That being said, I noticed that despite the language server saying the package isn't there, it's still functional.  Let me know if it actually runs the parser, but in the meantime, I'll get the import issue handled.

Thanks for using my package :)

**Comment by jnorvell** [comment]
When I try to run my app anyway I get the following runtime error:

`Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.`

**Comment by jnorvell** [comment]
Maybe add something like this to the project:  

file:  remark-obsidian.d.ts

`declare module “@thecae/remark-obsidian”;`

**Comment by heavycircle** [comment]
I think I have it fixed (or at least, it's working on mine).

Just update the package to `1.1.1` and let me know if there still are issues.

Thanks again :)

**Comment by jnorvell** [comment]
I've updated to 1.1.1 and I no longer get the errors, but this markdown doesn't seem to render for me in my example.


```
[[Link]]

![[Link]]

![[Link#^id]]

This is an %%inline%% comment.

%%
This is a block comment.

Block comments can span multiple lines.
%%

```
